g50:
    topo: g50                 # str: Name of the topology to be used.
    num_nodes: 50

    weight: null                # str: Metric used for edge weights in shortest path finding (optional).
    num_paths_per_pair: 4       # int: Number of paths per node pair.
    pred: 0                     # int/bool: Use predicted TMs (0=False).
    hist_len: 12                # int: Length of TM history to input.

    train_set:
        cluster: 0
        start: 0
        end: 200

    val_set:
        cluster: 0
        start: 200
        end: 240

    test_set:
        cluster: 0
        start: 240
        end: 280

    metric: MLU                 # str: Optimization metric (currently supports only 'MLU', not used).
    failure_id: null            # int: Failure scenario ID (optional).
# dynamic: 1                  # int/bool: Whether the topology is dynamic (1=True).
