# @package _global_
defaults:
    - /loader: base
    - /training: base            # default training configuration
    - /task: te                  # default task configuration
    - /dataset:
        - abilene
